### ISSUE TITLE
implementação do questionário

### ISSUE THREAD

**Issue by bismarckcesar** [i4n-v/NutriBook#12]
como desenvolvedor;
quero quero formular as perguntas do questionário;
para levantar os requisitos do sistema;

- [x] formular perguntas do questionário ;
- [x] aplicar perguntas do questionário;
- [x] coletar dados do questionário;

**Comment by HeitorGomesIF** [comment]
[Perguntas questionário.txt](https://github.com/i4n-v/NutriBook/files/6600501/Perguntas.questionario.txt)
Possíveis perguntas para o formulário.

**Comment by lilialnas** [comment]
@HeitorGomesIF cria um formulário no google com essas perguntas.

Perguntem no sentido de colher alguns requisitos também. 

1. Quais são as informações importantes do paciente que você avalia em cada consulta? Peso, dobras cutâneas, taxas de exames sanguíneos, avaliação de bioimpedância, medidas corporais.
2. Todo nutricionista faz uma anamnese do paciente também. Googlem!
3. Quais são as informações importantes no cadastro do alimento? Tabela nutricional, quantidade proteína, carboidratos, gordura?
3. É interessante também para o nutricionista, cadastrar o alimento, cadastrar a refeição e cadastrar algumas possíveis receitas?

Pergunta 2: coloca um checkbox para pessoa marcar e deixa a opção outros para que ela possa descrever.
Pergunta 3: super vazia e evitem usar o verbo 'achar'. Exemplo: Qual sua opinião sobre um sistema que faça o plano alimentar dos seus pacientes. 

Tentem diminuir as perguntas subjetivas, usuário tem preguiça de digitar, de escrever.
Utilizem também a escala de likert nas respostas.Oi aula de IHC, tututopom?

**Comment by lilialnas** [comment]
Gente, olhando a issue #11. Isso aqui é a entrevista ao invés de questionário hein?

**Comment by i4n-v** [comment]
@lilialnas Acredito que seja uma junção das duas, pois essa issue visa implementar, aplicar e coletar os dados do questionário

**Comment by lilialnas** [comment]
Então, vamos separar. Algumas perguntas serão para questionário e outras para entrevistas. 
A entrevista são perguntas subjetivas e a gente visa colher mais informações do que pode ter ficado seco d+ no questionário. Entendem?
