### ISSUE TITLE
compreensão das entidades do sistema

### ISSUE THREAD

**Issue by bismarckcesar** [i4n-v/NutriBook#13]
Procurar no google fichas de planos de alimentares, planilhas, outros sistemas. Começar a entender os termos, os campos e tabelas interessantes.

**Comment by HeitorGomesIF** [comment]
https://www.youtube.com/watch?v=LTWQhRJLNI8
DietBox, autodenominado o sistema mais completo do Brasil em relação a nutrição no geral (até lançarmos o nosso rs)

**Comment by i4n-v** [comment]
Esboço das entidades do sistema:

![NutriBook](https://user-images.githubusercontent.com/72396372/120842998-ea574280-c543-11eb-99c2-f7b799e9904e.png)

**Comment by lilialnas** [comment]
Então, gente! Um novo plano alimentar sempre é definido após uma avaliação.
O nutricionista além de cadastrar o paciente, cadastrar o plano alimentar, ele cadastra uma avaliação do paciente.
Essa avaliação contém o novo peso do paciente, taxa de metabolismo basal, novas medidas de região do corpo, novas medidas de dobras cutâneas, percentual de massa magra, massa de gordura. Essa avaliação é massa para acompanhar a evolução do paciente. E usaremos lá na frente em dashboard.
Saca um exemplo disso aqui: http://www.saudeemmovimento.com.br/saude/dobras/dobra_m7.htm

Uma outra entidade que podemos adicionar é de alimento. E vamos fazer assim: uma refeição contém um ou muitos alimentos. Exemplo de alimento: feijão, arroz, tomate.
A refeição seria a composição de vários alimentos. 
Na entidade alimento precisamos ter sua tabela nutricional (Googlem!)

**Comment by i4n-v** [comment]
**Mapeamento das entidades do sistemas, seus atributos e relacionamentos:**

![image](https://user-images.githubusercontent.com/72396372/122116610-3041bf80-cdfc-11eb-8454-a1ed1a0d2762.png)
