### ISSUE TITLE
Implementar página home do paciente

### ISSUE THREAD

**Issue by i4n-v** [i4n-v/NutriBook#33]
**Como** paciente;
**Quero** entrar na página inicial do sistema  com o meu usuário;
**Para** para utilizar as ferramentas do sistema;

- [x] Implementar front-end com tailwind;
- [x] Implementar back-end;

**Comment by fabio-fraga** [comment]
Para aplicar a migration adding_title_column_in_eating_plans_table use o comando:

_php artisan migrate_

Se quiser semear a tabela eating plans use o comando:

_php artisan db:seed --class=EatingPlanSeeder_

Se por algum motivo quiser desfazer a última migration (adding_title_column_in_eating_plans_table até então) use o comando:

_php artisan migrate:rollback_

Para mais informações sobre rollback, consulte: 

https://laravel.com/docs/8.x/migrations#rolling-back-migrations
