### ISSUE TITLE
 Levantamento das necessidades dos usuários (IHC)

### ISSUE THREAD

**Issue by i4n-v** [i4n-v/NutriBook#6]
Realizar entrevista (formular as perguntas antes para serem revisadas pelos professores) #12 ;
Aplicar questionário (perguntas a serem revisadas pelos professores) #12   ;
Analisar dados coletados #12 ;
Pesquisar e compreender as entidades relacionadas ao plano alimentar #13;

**Comment by lilialnas** [comment]
Vocês arrasam hein! Tou de olho!
