### ISSUE TITLE
Visão do Produto e Projeto

### ISSUE THREAD

**Issue by i4n-v** [i4n-v/NutriBook#7]
- [x] Procurar sistemas concorrentes e propor um diferencial;
- [x] Pensar se a forma como o sandbox foi realizado atende para melhorias e implementações futuras;
- [x] Quais seriam as novas funcionalidades do sistema de plano alimentar;
- [x] Tecnologias utilizadas;

**Comment by bismarckcesar** [comment]
Foi realizada uma pesquisa e encontramos alguns sites, a partir deles decidimos talvez tentar implementar algumas funcionalidades:

https://webdiet.com.br/ - tabela de anamnese.

https://nutrisoft.com.br/software-de-nutricao/ - como o nutricionista vai visualizar os paciente no seu perfil.

um diferencial a ser proposto é a visualização dos planos alimentares no site pelos pacientes.

**Comment by i4n-v** [comment]
O projeto sandBox não foi implementado visando futuras evoluções ou incrementos, devido a forma como o banco de dados foi implementado e a construção do código. Desse modo, decidimos utilizar as principais ideias do sandBox e aplica-las ao novo sistema Nutribook.

**Comment by i4n-v** [comment]
- Pretendemos implementar um perfil adequado ao paciente, para que o nutricionista possa visualizar coerentemente os dados e os planos alimentares atrelados ao paciente;
- Também decidimos adicionar novos campos ao usuário, visando a sua situação de saúde, alergias e etc, para que o nutricionista gerencie melhor o plano alimentar do paciente;
- Novas funcionalidades podem surgir(ou não kkk) ao longo do desenvolvimento.

**Comment by i4n-v** [comment]
As tecnologias que serão utilizadas no projeto, serão **Laravel** e **Tailwind**.

**Comment by lilialnas** [comment]
> * Pretendemos implementar um perfil adequado ao paciente, para que o nutricionista possa visualizar coerentemente os dados e os planos alimentares atrelados ao paciente;
> * Também decidimos adicionar novos campos ao usuário, visando a sua situação de saúde, alergias e etc, para que o nutricionista gerencie melhor o plano alimentar do paciente;
> * Novas funcionalidades podem surgir(ou não kkk) ao longo do desenvolvimento.

vão surgir novas funcionalidades sim! hahaha

**Comment by lilialnas** [comment]
A galera que tá fazendo a issue #8 tem que se aproveitar do que tá descrito aqui. @Giovannanascimento @huandersonlima
