### ISSUE TITLE
Implementação inicial do README.md

### ISSUE THREAD

**Issue by i4n-v** [i4n-v/NutriBook#8]
**Como** desenvolvedor;
**Quero** estruturar o arquivo **README.md**;
**Para** documentar e manter a visualização do projeto clara, com sua descrição, funcionalidades e equipe;

- [x] Criar arquivo **README.md**;
- [x] Estruturar e orgoanizar o arquivo;
- [x] Descrever o projeto NutriBook;

**Comment by lilialnas** [comment]
waiting for us!

**Comment by lilialnas** [comment]
Essa atividade ainda está com @huandersonlima  e @Giovannanascimento ??

Um readme, gente!!! Se arrastando para fazer um readme??
