### ISSUE TITLE
Prototipação do sistema NutriBook

### ISSUE THREAD

**Issue by i4n-v** [i4n-v/NutriBook#9]
**Como** desenvolvedor;
**Quero** implementar o protótipo do sistema;
**Para** tomar como base o desenvolvimento da aplicação;

- [x] Prototipar página de login;
- [x] Prototipar página de registro do nutricionista;
- [x] Prototipar página home do usuário;
- [x] Prototipar página de pesquisa por paciente;

**Comment by alowce** [comment]
O protótipo inicial foi criado no Figma. Ele pode ser acessado através do seguinte link:
https://www.figma.com/file/Z1XGUINyRjGtH60qZC3WbW/NutriBook?node-id=0%3A1

**Comment by alowce** [comment]
O protótipo ajustado (nova versão) pode ser acessado através do seguinte link:
https://www.figma.com/file/wznawoVfcTU9dBhXFShKsf/NutriBook-V.2?node-id=0%3A1

**Comment by lilialnas** [comment]
Finalizado com sucesso!
